version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
    networks:
      - nginx_network
networks:
  nginx_network:
    driver: bridge