// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v3.21.12
// source: api/management/v1/management.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationManagementBaseInformation = "/api.management.v1.Management/BaseInformation"
const OperationManagementCreateTestPlan = "/api.management.v1.Management/CreateTestPlan"
const OperationManagementGetTestPlaById = "/api.management.v1.Management/GetTestPlaById"
const OperationManagementUpdateTestPlan = "/api.management.v1.Management/UpdateTestPlan"

type ManagementHTTPServer interface {
	BaseInformation(context.Context, *emptypb.Empty) (*BaseInfoReply, error)
	CreateTestPlan(context.Context, *CreateTestPlanRequest) (*CreateTestPlanReply, error)
	GetTestPlaById(context.Context, *GetTestPlanRequest) (*GetTestPlanReply, error)
	UpdateTestPlan(context.Context, *UpdateTestPlanRequest) (*emptypb.Empty, error)
}

func RegisterManagementHTTPServer(s *http.Server, srv ManagementHTTPServer) {
	r := s.Route("/")
	r.GET("v1/api/management/info", _Management_BaseInformation0_HTTP_Handler(srv))
	r.POST("v1/api/management/testplan", _Management_CreateTestPlan0_HTTP_Handler(srv))
	r.PUT("v1/api/management/testplan", _Management_UpdateTestPlan0_HTTP_Handler(srv))
	r.GET("v1/api/management/testplan/{id}", _Management_GetTestPlaById0_HTTP_Handler(srv))
}

func _Management_BaseInformation0_HTTP_Handler(srv ManagementHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationManagementBaseInformation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BaseInformation(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BaseInfoReply)
		return ctx.Result(200, reply)
	}
}

func _Management_CreateTestPlan0_HTTP_Handler(srv ManagementHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTestPlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationManagementCreateTestPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTestPlan(ctx, req.(*CreateTestPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTestPlanReply)
		return ctx.Result(200, reply)
	}
}

func _Management_UpdateTestPlan0_HTTP_Handler(srv ManagementHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTestPlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationManagementUpdateTestPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTestPlan(ctx, req.(*UpdateTestPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Management_GetTestPlaById0_HTTP_Handler(srv ManagementHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTestPlanRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationManagementGetTestPlaById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTestPlaById(ctx, req.(*GetTestPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTestPlanReply)
		return ctx.Result(200, reply)
	}
}

type ManagementHTTPClient interface {
	BaseInformation(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *BaseInfoReply, err error)
	CreateTestPlan(ctx context.Context, req *CreateTestPlanRequest, opts ...http.CallOption) (rsp *CreateTestPlanReply, err error)
	GetTestPlaById(ctx context.Context, req *GetTestPlanRequest, opts ...http.CallOption) (rsp *GetTestPlanReply, err error)
	UpdateTestPlan(ctx context.Context, req *UpdateTestPlanRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type ManagementHTTPClientImpl struct {
	cc *http.Client
}

func NewManagementHTTPClient(client *http.Client) ManagementHTTPClient {
	return &ManagementHTTPClientImpl{client}
}

func (c *ManagementHTTPClientImpl) BaseInformation(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*BaseInfoReply, error) {
	var out BaseInfoReply
	pattern := "v1/api/management/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationManagementBaseInformation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ManagementHTTPClientImpl) CreateTestPlan(ctx context.Context, in *CreateTestPlanRequest, opts ...http.CallOption) (*CreateTestPlanReply, error) {
	var out CreateTestPlanReply
	pattern := "v1/api/management/testplan"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationManagementCreateTestPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ManagementHTTPClientImpl) GetTestPlaById(ctx context.Context, in *GetTestPlanRequest, opts ...http.CallOption) (*GetTestPlanReply, error) {
	var out GetTestPlanReply
	pattern := "v1/api/management/testplan/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationManagementGetTestPlaById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ManagementHTTPClientImpl) UpdateTestPlan(ctx context.Context, in *UpdateTestPlanRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "v1/api/management/testplan"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationManagementUpdateTestPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
