// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"galileo/ent/apicategory"
	"galileo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApiCategoryDelete is the builder for deleting a ApiCategory entity.
type ApiCategoryDelete struct {
	config
	hooks    []Hook
	mutation *ApiCategoryMutation
}

// Where appends a list predicates to the ApiCategoryDelete builder.
func (acd *ApiCategoryDelete) Where(ps ...predicate.ApiCategory) *ApiCategoryDelete {
	acd.mutation.Where(ps...)
	return acd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (acd *ApiCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ApiCategoryMutation](ctx, acd.sqlExec, acd.mutation, acd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (acd *ApiCategoryDelete) ExecX(ctx context.Context) int {
	n, err := acd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (acd *ApiCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apicategory.Table, sqlgraph.NewFieldSpec(apicategory.FieldID, field.TypeInt))
	if ps := acd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, acd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	acd.mutation.done = true
	return affected, err
}

// ApiCategoryDeleteOne is the builder for deleting a single ApiCategory entity.
type ApiCategoryDeleteOne struct {
	acd *ApiCategoryDelete
}

// Where appends a list predicates to the ApiCategoryDelete builder.
func (acdo *ApiCategoryDeleteOne) Where(ps ...predicate.ApiCategory) *ApiCategoryDeleteOne {
	acdo.acd.mutation.Where(ps...)
	return acdo
}

// Exec executes the deletion query.
func (acdo *ApiCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := acdo.acd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apicategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (acdo *ApiCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := acdo.Exec(ctx); err != nil {
		panic(err)
	}
}
