name: core.api
server:
  http:
    addr: 0.0.0.0:8097
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/galileo
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    producer_return_successes: true
    producer_return_errors: true
    producer_timeout: 5s
trace:
  endpoint: http://127.0.0.1:14268/api/traces
auth:
  jwt_key: hqFr%3ddt32DGlSTOI5cO6@TH#fFwYnP$S
service:
  user:
    endpoint: discovery:///core.user.scheduler
  management:
    endpoint: discovery:///galileo.management.scheduler
