// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.0
// - protoc             v3.21.12
// source: api/analytics/v1/analytics.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAnalyticsHelloWorld = "/api.analytics.v1.Analytics/HelloWorld"

type AnalyticsHTTPServer interface {
	HelloWorld(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

func RegisterAnalyticsHTTPServer(s *http.Server, srv AnalyticsHTTPServer) {
	r := s.Route("/")
	r.GET("v1/api/analytics", _Analytics_HelloWorld0_HTTP_Handler(srv))
}

func _Analytics_HelloWorld0_HTTP_Handler(srv AnalyticsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalyticsHelloWorld)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HelloWorld(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type AnalyticsHTTPClient interface {
	HelloWorld(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type AnalyticsHTTPClientImpl struct {
	cc *http.Client
}

func NewAnalyticsHTTPClient(client *http.Client) AnalyticsHTTPClient {
	return &AnalyticsHTTPClientImpl{client}
}

func (c *AnalyticsHTTPClientImpl) HelloWorld(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "v1/api/analytics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalyticsHelloWorld))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
