// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Api is the predicate function for api builders.
type Api func(*sql.Selector)

// ApiCategory is the predicate function for apicategory builders.
type ApiCategory func(*sql.Selector)

// ApiHistory is the predicate function for apihistory builders.
type ApiHistory func(*sql.Selector)

// ApiStatistics is the predicate function for apistatistics builders.
type ApiStatistics func(*sql.Selector)

// ApiTag is the predicate function for apitag builders.
type ApiTag func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// Testcase is the predicate function for testcase builders.
type Testcase func(*sql.Selector)

// TestcaseSuite is the predicate function for testcasesuite builders.
type TestcaseSuite func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
